// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchContributions(arg1:string):Promise<Array<main.Contribution>>;

export function GenerateAndPlayMusic(arg1:Array<main.Contribution>):Promise<string>;
