// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchContributions(arg1) {
  return window['go']['main']['App']['FetchContributions'](arg1);
}

export function GenerateAndPlayMusic(arg1) {
  return window['go']['main']['App']['GenerateAndPlayMusic'](arg1);
}
